name: flutter_application_api_autos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_material_design_icons: ^1.1.7447
  flutter_mdi_icons: ^0.1.3
  flutter_slidable: ^3.1.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/logoUSM.png
  uses-material-design: true
